# Required
github_username: "hacksearch"
github_password: "Information@2023"

# Optional (comment out if not using)
# github_totp_seed: "ABCDEF1234567890" # Obtained via https://github.com/settings/security
